### ISSUE TITLE
Peer to peer code review 14/04/2023

### ISSUE THREAD

**Issue by ShaliniNayan** [ShaliniNayan/Shalini_Portfolio#12]
All issues are welcome here

**Comment by 10-menachi** [comment]
I would recommend you use more responsive measurements such as %, rem, and em as opposed to px, as they scale well with the device width.
Otherwise, the project is fantastic.

**Comment by ShaliniNayan** [comment]
Noted Thank you.

**Comment by musangamfure** [comment]
Hello @ShaliniNayan,

Congratulations on an outstanding job👏🎉🎉 on creating the popup window using JS.
 
![good job](https://user-images.githubusercontent.com/123179856/231969953-90f2b370-e597-4d14-8713-b9005e73086b.gif)

Keep improving your design layout to match with figma design especially on desktop version specifically on buttons.

Keep growing and Happy coding💪💪
